apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: kyverno-test.yaml
policies:
- policy.yaml
resources:
- tigger-cm.yaml
targetResources:
- raw-secret.yaml
results:
- kind: Secret
  patchedResource: mutated-secret.yaml
  policy: mutate-existing-secret
  resources:
  - secret-1
  result: pass
  rule: mutate-secret-on-configmap-create